# Generated by Django 5.2.7 on 2025-11-05 00:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('property_type', models.CharField(choices=[('house', 'Maison'), ('apartment', 'Appartement'), ('villa', 'Villa'), ('studio', 'Studio'), ('land', 'Terrain')], max_length=20, verbose_name='Type de propriété')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude (GPS)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude (GPS)')),
                ('price_per_room', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix par chambre (FCFA)')),
                ('number_of_rooms', models.PositiveIntegerField(verbose_name='Nombre de pièces')),
                ('number_of_bedrooms', models.PositiveIntegerField(verbose_name='Nombre de chambres')),
                ('number_of_bathrooms', models.PositiveIntegerField(default=1, verbose_name='Nombre de salles de bain')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie (m²)')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'Louée'), ('pending', 'En attente'), ('unavailable', 'Indisponible')], default='available', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ARTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_scene_url', models.URLField(blank=True, null=True, verbose_name='URL de la scène AR')),
                ('ar_model_file', models.FileField(blank=True, null=True, upload_to='ar_models/', verbose_name='Fichier modèle AR')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions de visite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ar_tour', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Visite AR',
                'verbose_name_plural': 'Visites AR',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='Image')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Image de propriété',
                'verbose_name_plural': 'Images de propriétés',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
