# Generated by Django 5.2.7 on 2025-11-05 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artour',
            name='property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_tour', to='properties.property', verbose_name='Propriété'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('bedroom', 'Chambre'), ('living_room', 'Salon'), ('kitchen', 'Cuisine'), ('bathroom', 'Salle de bain'), ('dining_room', 'Salle à manger'), ('office', 'Bureau'), ('balcony', 'Balcon'), ('other', 'Autre')], default='bedroom', max_length=20, verbose_name='Type de pièce')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la chambre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Superficie (m²)')),
                ('floor_number', models.IntegerField(default=1, verbose_name='Étage')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['order', 'floor_number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='artour',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_tour', to='properties.room', verbose_name='Chambre'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='properties.room', verbose_name='Chambre (optionnel)'),
        ),
    ]
