# Generated by Django 5.2.8 on 2026-02-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_artour_property_room_artour_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_type',
            field=models.CharField(choices=[('normal', 'Photo normale'), ('panorama_360', 'Photo panoramique 360°')], default='normal', max_length=20, verbose_name="Type d'image"),
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Formats supportés: mp4, webm', upload_to='property_videos/', verbose_name='Vidéo')),
                ('video_type', models.CharField(choices=[('walkthrough', 'Visite guidée'), ('360_video', 'Vidéo 360°')], default='walkthrough', max_length=20, verbose_name='Type de vidéo')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property', verbose_name='Propriété')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='properties.room', verbose_name='Chambre (optionnel)')),
            ],
            options={
                'verbose_name': 'Vidéo de propriété',
                'verbose_name_plural': 'Vidéos de propriétés',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
