# Generated by Django 6.0.2 on 2026-07-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_image_type_and_property_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySplat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('splat_file', models.FileField(blank=True, help_text='Formats : .splat, .ply, .ksplat', upload_to='property_splats/', verbose_name='Fichier splat')),
                ('status', models.CharField(choices=[('pending', 'En file'), ('processing', 'Reconstruction…'), ('ready', 'Prête'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name='Erreur')),
                ('frames_extracted', models.PositiveIntegerField(default=0, verbose_name='Images extraites')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splats', to='properties.property', verbose_name='Propriété')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splats', to='properties.room', verbose_name='Pièce')),
                ('source_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splat_jobs', to='properties.propertyvideo', verbose_name='Vidéo source')),
            ],
            options={
                'verbose_name': 'Scène 3D splat',
                'verbose_name_plural': 'Scènes 3D splat',
                'ordering': ['-created_at'],
            },
        ),
    ]
