# Generated by Django 6.0.2 on 2026-09-07 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_splat'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_period',
            field=models.CharField(choices=[('month', 'Par mois'), ('night', 'Par nuit')], default='month', max_length=10, verbose_name='Période de tarif'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_mode',
            field=models.CharField(choices=[('entire', 'Bien entier (résidence / logement complet)'), ('by_room', 'Par chambre')], default='entire', max_length=20, verbose_name='Mode de location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_room',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'Maison'), ('apartment', 'Appartement'), ('residence', 'Résidence'), ('villa', 'Villa'), ('studio', 'Studio'), ('land', 'Terrain')], max_length=20, verbose_name='Type de propriété'),
        ),
    ]
